### ISSUE TITLE
Result is so sparse

### ISSUE THREAD

**Issue by chester256** [CKchaos/scn2pointcloud_tool#1]
Thanks for your work. The generated point cloud seems to be very sparse. What would be the problem? Below is a generated house point cloud.
<img width="781" alt="Screen Shot 2019-09-09 at 21 50 08" src="https://user-images.githubusercontent.com/18751402/64536757-3e6fcb80-d34c-11e9-88d6-2ed0c4a2c1c5.png">

**Comment by CKchaos** [comment]
Hi! You can edit the variable 'dim' in demo.py to a larger number, and then you will get more dense outputs. But if you would like to get a pretty compact output, you might need to modify the function 'get_data' in 'SUNCGtoolbox/gaps/apps/scn2pointcould/scn2pointcould.cpp' as well. In the current version, the implementation of 'get_data' is not elegant at all. I wrote the code like that just for quick deployment because of a conference deadline.

**Comment by chester256** [comment]
Thanks for your reply. Where to place the .mtl files and texture files? The demo code only requires .obj file. Thanks.

**Comment by CKchaos** [comment]
The path of .mtl files should be stated in the .obj files, just like "mtllib ../XXXX/xxx.mtl", and the path of texture image files should be stated in the .mtl files like "map_Kd ../XXXX/xxx.jpg". You can also get to know the rules of .obj files by google.com.

**Comment by chester256** [comment]
Thanks for your reply. I have tried to modify 'dim' in demo.py. But it costs too much time to get a dense output. Is there any faster implementation?

**Comment by CKchaos** [comment]
You are right. The current implementation is time-consuming, cause every point in the output is sampled from the .obj file. The algorithm needs to compute which coordinates should be sampled and find its corresponding color value in .mtl file or texture images. So it will cost pretty much time to process a larger number of points. Unfortunately, I haven't found a better implementation which implements the same function as this repo.

**Comment by chester256** [comment]
Thanks for your reply. I found a nice alternative called CloudCompare, which can sample points very fast. But it cannot get the object attribute of each point. So obj file needs to be split into different models/objects, and finally combine them together after sampling points.

**Comment by CKchaos** [comment]
Yes, CloudCompare is a useful tool in the field of points cloud processing.

**Comment by jediofgever** [comment]
how do you visualize generated point cloud  ?

**Comment by chester256** [comment]
> how do you visualize generated point cloud ?

Open3D python: http://www.open3d.org/docs/release/tutorial/Basic/python_interface.html
