### ISSUE TITLE
Is the SUNCGtoolbox original one?

### ISSUE THREAD

**Issue by chester256** [CKchaos/scn2pointcloud_tool#2]
Sorry to bother you again. I used the SUNCGtoolbox in this repo to generate .obj files. But I find that some materials (in .mtl) do not have path to texture. For instance,
```
newmtl m43
Ka 0.64 0.64 0.64
Kd 0.64 0.64 0.64
Ns 50
map_Kd ../../texture/wood_14_5.jpg

newmtl m44
Ka 0.778483 0.787897 0.623463
Kd 0.776471 0.784314 0.619608
Ns 5
```
m43 has the texture path but m44 does not. Is this normal? Or I have some compilation problems of the toolbox?

**Comment by CKchaos** [comment]
Google "MTL files definition". You will find what you need to know.
